spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    hibernate.ddl-auto: none

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml
    enabled: true
    drop-first: true

  redis:
    host: localhost
    port: 6379

token:
  signing:
    key: eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4
    expiration-ms: 200000